// lib/constants/musicData.ts

// Countries list (ISO standard)
export const countries = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
  'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
  'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
  'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
  'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)',
  'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of the Congo', 'Denmark',
  'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea',
  'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
  'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
  'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel',
  'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
  'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania',
  'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
  'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
  'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau',
  'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
  'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
  'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands',
  'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
  'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
  'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda',
  'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
  'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
];

export const territories = [
  // Global
  'Worldwide',
  'World excluding United States',
  'World excluding United Kingdom',
  'Rest of World (ROW)',

  // Major Single Territories
  'United States',
  'Canada',
  'United Kingdom',
  'Ireland',
  'Japan',

  // Regional Groupings
  'North America (US & Canada)',
  'Europe',
  'European Union (EU)',
  'Latin America (LATAM)',
  'Caribbean',
  'Middle East and North Africa (MENA)',
  'Sub-Saharan Africa',
  'Asia-Pacific (APAC)',
  'Australia and New Zealand',

  // Carve-outs (commonly negotiated in co-pub deals)
  'United States and Canada',
  'United Kingdom and Ireland',
  'Europe excluding United Kingdom',
  'World excluding Japan'
];

// Genre to Subgenre mapping
export const genreSubgenreMap: Record<string, string[]> = {
  'African': ['African Dancehall', 'African Reggae', 'Afrikaans', 'Afro House', 'Afro Soul', 'Afro-Beat', 'Afro-folk', 'Afro-fusion', 'Afro-Pop', 'Afrobeats', 'Alte', 'Amapiano', 'Benga', 'Bongo-Flava', 'Chimurenga', 'Coupé-Décalé', 'Fuji', 'Genge', 'Gqom', 'Highlife', 'Kizomba', 'Kuduro', 'Kwaito', 'Kwassa', 'Mapouka', 'Maskandi', 'Mbalax', 'Ndombolo', 'Shangaan Electro', 'Soukous', 'Taarab', 'Zouglou'],
  'Alternative': ['Chinese Alt', 'College Rock', 'EMO', 'Goth Rock', 'Grunge', 'Indie Egyptian', 'Indie Levant', 'Indie Maghreb', 'Indie Pop', 'Indie Rock', 'Korean Indie', 'New Wave', 'Pop Punk', 'Punk', 'Turkish Alternative'],
  'Arabic': ['Arabic Pop', 'Dabke', 'Islamic', 'Khaleeji', 'Khaleeji Jalsat', 'Khaleeji Shailat', 'Levant', 'Maghreb Rai', 'North African'],
  'Blues': ['Acoustic Blues', 'Chicago Blues', 'Classic Blues', 'Contemporary Blues', 'Country Blues', 'Delta Blues', 'Electric Blues'],
  'Brazilian': ['Axé', 'Baile Funk', 'Bossa Nova', 'Choro', 'Forró', 'Frevo', 'MPB', 'Pagode', 'Samba', 'Sertanejo'],
  'Children\'s Music': ['Lullabies', 'Sing-Along', 'Stories'],
  'Chinese': ['Chinese Classical', 'Chinese Flute', 'Chinese Opera', 'Chinese Orchestral', 'Chinese Regional Folk', 'Chinese Strings', 'Taiwanese Folk', 'Tibetan Native Music'],
  'Christian & Gospel': ['CCM', 'Christian Metal', 'Christian Pop', 'Christian Rap', 'Christian Rock', 'Classic Christian', 'Contemporary Gospel', 'Gospel', 'Praise & Worship', 'Southern Gospel', 'Traditional Gospel'],
  'Classical': ['Art Song', 'Avant-Garde', 'Baroque Era', 'Brass & Woodwinds', 'Cantata', 'Cello', 'Chamber Music', 'Chant', 'Choral', 'Classical Crossover', 'Classical Era', 'Contemporary Era', 'Electronic', 'Guitar', 'Impressionist', 'Medieval Era', 'Minimalism', 'Modern Era', 'Opera', 'Oratorio', 'Orchestral', 'Percussion', 'Piano', 'Renaissance', 'Romantic Era', 'Sacred', 'Solo Instrumental', 'Violin'],
  'Comedy': ['Novelty', 'Standup Comedy'],
  'Country': ['Alternative Country', 'Americana', 'Bluegrass', 'Contemporary Bluegrass', 'Contemporary Country', 'Country Gospel', 'Country Hip-Hop/Rap', 'Honky Tonk', 'Outlaw Country', 'Thai Country', 'Traditional Bluegrass', 'Traditional Country', 'Urban Cowboy'],
  'Cuban': ['Bolero', 'Chachacha', 'Guajira', 'Guaracha', 'Mambo', 'Son', 'Timba'],
  'Dance': ['Breakbeat', 'Garage', 'Hardcore', 'House', 'Jungle/Drum\'n\'bass', 'Maghreb Dance', 'Techno', 'Trance'],
  'Easy Listening': ['Lounge', 'Swing'],
  'Electronic': ['Ambient', 'Bass', 'Downtempo', 'Dubstep', 'Electro-Cha\'abi', 'Electronica', 'IDM/Experimental', 'Industrial', 'Levant Electronic', 'Maghreb Electronic'],
  'Folk': ['Iraqi Folk', 'Khaleeji Folk'],
  'Hip Hop/Rap': ['Alternative Rap', 'Chinese Hip-Hop', 'Dirty South', 'East Coast Rap', 'Egyptian Hip-Hop', 'Gangsta Rap', 'Ghanaian Drill', 'Hardcore Rap', 'Hip-Hop', 'Khaleeji Hip-Hop', 'Korean Hip-Hop', 'Latin Rap', 'Levant Hip-Hop', 'Maghreb Hip-Hop', 'Old School Rap', 'Rap', 'Russian Hip-Hop', 'South African Hip-Hop', 'Turkish Hip-Hop/Rap', 'UK Hip Hop', 'Underground Rap', 'West Coast Rap'],
  'Holiday': ['Christmas', 'Christmas: Children\'s', 'Christmas: Classic', 'Christmas: Classical', 'Christmas: Country', 'Christmas: Jazz', 'Christmas: Modern', 'Christmas: Pop', 'Christmas: R&B', 'Christmas: Religious', 'Christmas: Rock', 'Easter', 'Halloween', 'Thanksgiving'],
  'Indian': ['Assamese', 'Bengali', 'Bhojpuri', 'Bollywood', 'Carnatic Classical', 'Devotional & Spiritual', 'Ghazals', 'Gujarati', 'Haryanvi', 'Hindustani Classical', 'Indian Classical', 'Indian Folk', 'Indian Pop', 'Kannada', 'Malayalam', 'Marathi', 'Odia', 'Punjabi', 'Punjabi Pop', 'Rabindra Sangeet', 'Rajasthani', 'Regional Indian', 'Sufi', 'Tamil', 'Telugu', 'Urdu'],
  'Jazz': ['Avant-Garde Jazz', 'Bebop', 'Big Band', 'Contemporary Jazz', 'Cool Jazz', 'Crossover Jazz', 'Dixieland', 'Ethio Jazz', 'Fusion', 'Hard Bop', 'Latin Jazz', 'Mainstream Jazz', 'Ragtime', 'Smooth Jazz', 'Trad Jazz', 'Vocal Jazz'],
  'Jewish': ['Jewish Holidays', 'Klezmer'],
  'Korean': ['Korean Traditional'],
  'Latin': ['Alternative & Rock in Spanish', 'Baladas y Boleros', 'Contemporary Latin', 'Latin Jazz', 'Latin Urban', 'Pop in Spanish', 'Raices', 'Regional Mexicano', 'Salsa y Tropical'],
  'New Age': ['Healing', 'Meditation', 'Nature', 'Relaxation', 'Travel', 'Yoga'],
  'Pop': ['Adult Contemporary', 'Britpop', 'Cantopop', 'Egyptian Pop', 'Indo Pop', 'Iraqi Pop', 'K-Pop', 'Khaleeji Pop', 'Korean Folk-Pop', 'Levant Pop', 'Maghreb Pop', 'Malaysian Pop', 'Mandopop', 'Manilla Sound', 'Oldies', 'Original Pilipino Music', 'Pinoy Pop', 'Pop/Rock', 'Russian Pop', 'Shows', 'Soft Rock', 'T-Pop', 'Tai-Pop', 'Teen Pop', 'Thai Pop', 'Turkish Pop'],
  'R&B/Soul': ['Contemporary R&B', 'Disco', 'Doo Wop', 'Funk', 'Motown', 'Neo-Soul', 'Soul'],
  'Reggae': ['Dub', 'Lovers Rock', 'Modern Dancehall', 'Roots Reggae', 'Ska'],
  'Rock': ['Adult Alternative', 'American Trad Rock', 'Arena Rock', 'Blues-Rock', 'British Invasion', 'Chinese Rock', 'Death Metal/Black Metal', 'Glam Rock', 'Hair Metal', 'Hard Rock', 'Heavy Metal', 'Jam Bands', 'Korean Rock', 'Prog-Rock/Art Rock', 'Psychedelic', 'Rock & Roll', 'Rockabilly', 'Roots Rock', 'Russian Rock', 'Singer/Songwriter', 'Southern Rock', 'Surf', 'Tex-Mex', 'Turkish Rock'],
  'Russian': ['Russian Bard', 'Russian Chanson', 'Russian Romance'],
  'Singer/Songwriter': ['Alternative Folk', 'Contemporary Folk', 'Contemporary Singer/Songwriter', 'Folk-Rock', 'New Acoustic', 'Traditional Folk'],
  'Soundtrack': ['Foreign Cinema', 'Musicals', 'Original Score', 'Sound Effects', 'Soundtrack', 'TV Soundtrack', 'Video Game'],
  'Tarab': ['Egyptian Tarab', 'Iraqi Tarab', 'Khaleeji Tarab'],
  'Turkish': ['Arabesk', 'Fantezi', 'Halk', 'Religious', 'Sanat', 'Özgün'],
  'Vocal': ['Standards', 'Traditional Pop', 'Trot', 'Vocal Pop'],
  'Worldwide': ['Asia', 'Australia', 'Cajun', 'Calypso', 'Caribbean', 'Celtic', 'Celtic Folk', 'Contemporary Celtic', 'Dangdut', 'Dini', 'Europe', 'Fado', 'Farsi', 'Flamenco', 'France', 'Hawaii', 'Iberia', 'Indonesian Religious', 'Israeli', 'Japan', 'North America', 'Polka', 'Soca', 'South Africa', 'South America', 'Tango', 'Traditional Celtic', 'Worldbeat', 'Zydeco'],
};

// Writer roles
export const writerRoles = [
  'Adapter', 'Adapter (Religious Text)', 'Adapter (Traditional Text)', 'Arranger', 
  'Arranger (Traditional)', 'Assistant Arranger', 'Based on the Work of', 'Book', 
  'Brass Arranger', 'Cadenza', 'Choir Arranger', 'Chorus Arranger', 'Co-Arranger', 
  'Co-Composer', 'Composer', 'Composition Ascribed to', 'Copyist', 'Horn Arranger', 
  'Keyboard Arranger', 'Librettist', 'Libretto Editing', 'Lyrics', 'Original Arranger', 
  'Orchestrator','Percussion Arranger', 'Poetry', 'Reconstruction', 'Revision',  
  'Saxophone Arranger', 'Score Editor', 'Score Preparation', 'Screenwriter', 'Songwriter', 
  'String Arranger', 'Text', 'Transcription', 'Translation', 'Trumpet Arranger', 
  'Vocal Adapter', 'Vocal Arranger', 'Wind Arranger', 'Woodwind Arranger', 'Writer'
];

// Production and Engineering roles
export const productionRoles = [
  "Additional Engineer",
  "Arranger",
  "Art Production",
  "Assistant Editing Engineer",
  "Assistant Engineer",
  "Assistant Mastering Engineer",
  "Assistant Mixing Engineer",
  "Assistant Producer",
  "Assistant Recording Engineer",
  "Assistant Strings Engineer",
  "Associate Producer",
  "Audio Engineer",
  "Audio Restoration",
  "Audio Technician",
  "Balance Engineer",
  "Bass Technician",
  "Camera Operator",
  "Choir Master",
  "Cinematography",
  "Co-Executive Producer",
  "Co-Producer",
  "Compilation Producer",
  "Computer Graphics",
  "Concert Producer",
  "Concert Production",
  "Cover Art",
  "Cover Photography",
  "Creative Director",
  "Drawing",
  "Drum Technician",
  "Editing Engineer",
  "Engineer",
  "Engraving",
  "Equipment Technician",
  "Executive Producer",
  "Film Direction",
  "Film Editor",
  "Film Producer",
  "Graphic Design",
  "Guitar Technician",
  "Harpsichord Technician",
  "Harpsichord Tuner",
  "Illustrator",
  "Immersive Audio Engineer",
  "Immersive Mastering Engineer",
  "Immersive Mixing Engineer",
  "Keyboard Technician",
  "Lighting Design",
  "Lithography",
  "Live Mastering Engineer",
  "Live Production",
  "Live Recording Engineer",
  "Mastering Engineer",
  "Mixing Engineer",
  "Music Supervisor",
  "Organ Technician",
  "Original Engineering",
  "Original Mastering Engineer",
  "Original Mixing Engineer",
  "Original Producer",
  "Package Designer",
  "Package Design",
  "Paintings",
  "Photo Editor",
  "Photography",
  "Piano Technician",
  "Piano Tuner",
  "Producer",
  "Post Production Assistant",
  "Post Production Director",
  "Post Production Editor",
  "Post Production Engineer",
  "Post Production Mixing Engineer",
  "Post Production Supervisor",
  "Production",
  "Recording Engineer",
  "Recording Supervisor",
  "Recording Technician",
  "Reissue Producer",
  "Remix Producer",
  "Research",
  "Score Producer",
  "Set Designer",
  "Sound Design",
  "Soundtrack Producer",
  "Special Effects",
  "Stage Director",
  "Stage Manager",
  "Stage Technician",
  "Strings Engineer",
  "Studio Personnel",
  "Studio Technician",
  "Stylist",
  "Tape Editor",
  "Tape Operator",
  "Tape Restoration",
  "Tonmeister",
  "Tracking Engineer",
  "Typesetting",
  "Typography",
  "Video Director",
  "Video Editor",
  "Video Producer",
  "Video Production",
  "Videography",
  "Vocal Mixing Engineer",
  "Vocal Producer",
  "Vocal Recording Engineer",
  "Wardrobe"
];

// Performer roles
export const performerRoles = [
  'Acrobat',
  'Action Choreographer',
  'Action Director',
  'Actor',
  'Animal Trainer',
  'Announcer',
  'Art Director',
  'Artistic Director',
  'Assistant Art Director',
  'Assistant Choreographer',
  'Assistant Director',
  'Assistant Fight Choreographer',
  'Associate Choreographer',
  'Atmosphere',
  'Background',
  'Background Singer',
  'Ballet Master',
  'Bit Part',
  'Body Double',
  'Boom Operator',
  'Casting',
  'Casting Associate',
  'Casting Consultant',
  'Character Actor',
  'Choreographer',
  'Chorus',
  'Clapper Loader',
  'Co-Host',
  'Comedian',
  'Commentator',
  'Conductor',
  'Continuity',
  'Continuity Tutor',
  'Contortionist',
  'Costume Design',
  'Costume Supervisor',
  'Creative Director',
  'Creature Design',
  'Crowd Wrangler',
  'Dancer',
  'Dialect Coach',
  'Director',
  'Director of Photography',
  'Diver',
  'DJ',
  'Dog Trainer',
  'Double',
  'Driver',
  'Editor',
  'Ensemble',
  'Executive In Charge Of Production',
  'Executive Producer',
  'Extra',
  'Fight Choreographer',
  'Fight Coordinator',
  'Fight Director',
  'Fire Performer',
  'First Assistant Director',
  'Flight Coordinator',
  'Foley',
  'Foley Artist',
  'Gaffer',
  'Guest',
  'Guest Host',
  'Guest Star',
  'Hand Double',
  'Host',
  'Illusionist',
  'Impersonator',
  'Interviewee',
  'Interviewer',
  'Juggler',
  'Key Grip',
  'Lighting Camera',
  'Lighting Director',
  'Lighting Technician',
  'Line Producer',
  'Lyricist',
  'Magician',
  'Makeup Artist',
  'Marine Coordinator',
  'Master of Ceremonies',
  'Mime',
  'Mixing Engineer',
  'Moderator',
  'Model',
  'Musician',
  'Narrator',
  'Newscaster',
  'On Set Computer Playback',
  'Opening Act',
  'Orchestrator',
  'Panelist',
  'Performer',
  'Photo Double',
  'Pilot',
  'Presenter',
  'Principal',
  'Producer',
  'Production Assistant',
  'Production Coordinator',
  'Production Designer',
  'Production Manager',
  'Production Staff',
  'Programmer',
  'Prompter',
  'Props',
  'Public Address Announcer',
  'Puppeteer',
  'Radio Announcer',
  'Reader',
  'Recurring Character',
  'Reporter',
  'Rigger',
  'Ring Announcer',
  'Ringleader',
  'Ringmaster',
  'Second Assistant Director',
  'Second Unit Director',
  'Security',
  'Set Decorator',
  'Set Designer',
  'Singer',
  'Skateboarder',
  'Skater',
  'Soloist',
  'Sound',
  'Sound Designer',
  'Sound Editor',
  'Sound Effects',
  'Sound Engineer',
  'Sound Mixer',
  'Sound Recordist',
  'Special Effects',
  'Special Guest',
  'Stand In',
  'Still Photographer',
  'Stunt Coordinator',
  'Stunt Double',
  'Stunt Driver',
  'Stunt Performer',
  'Stunts',
  'Supporting Actor',
  'Surfer',
  'Talent',
  'Talent Coordinator',
  'Technical Director',
  'Teleprompter',
  'Third Assistant Director',
  'Translator',
  'Tutor',
  'Understudy',
  'Variety Artist',
  'Video Assist Operator',
  'Violinist',
  'Visual Effects',
  'Voice',
  'Voice Actor',
  'Voice Director',
  'Voice Over',
  'Wardrobe',
  'Wardrobe Supervisor',
  'Weapons Master',
  'Wrangler',
  'Writer',
];

// PRO/CMO organizations
export const proOrganizations = [
  { code: 'ASCAP', name: 'ASCAP', country: 'United States' },
  { code: 'BMI', name: 'BMI', country: 'United States' },
  { code: 'SESAC', name: 'SESAC', country: 'United States' },
  { code: 'PRS', name: 'PRS for Music', country: 'United Kingdom' },
  { code: 'SACEM', name: 'SACEM', country: 'France' },
  { code: 'GEMA', name: 'GEMA', country: 'Germany' },
  { code: 'SIAE', name: 'SIAE', country: 'Italy' },
  { code: 'SGAE', name: 'SGAE', country: 'Spain' },
  { code: 'SABAM', name: 'SABAM', country: 'Belgium' },
  { code: 'BUMA', name: 'BUMA/STEMRA', country: 'Netherlands' },
  { code: 'SUISA', name: 'SUISA', country: 'Switzerland' },
  { code: 'SOCAN', name: 'SOCAN', country: 'Canada' },
  { code: 'APRA', name: 'APRA AMCOS', country: 'Australia' },
  { code: 'JASRAC', name: 'JASRAC', country: 'Japan' },
  { code: 'KOMCA', name: 'KOMCA', country: 'South Korea' },
  { code: 'SACM', name: 'SACM', country: 'Mexico' },
  { code: 'SCD', name: 'SCD', country: 'Chile' },
  { code: 'SADAIC', name: 'SADAIC', country: 'Argentina' },
  { code: 'ABRAMUS', name: 'ABRAMUS', country: 'Brazil' },
  { code: 'ECAD', name: 'ECAD', country: 'Brazil' },
  { code: 'SAYCO', name: 'SAYCO', country: 'Colombia' },
  { code: 'SAYCE', name: 'SAYCE', country: 'Ecuador' },
  { code: 'APDAYC', name: 'APDAYC', country: 'Peru' },
  { code: 'AGADU', name: 'AGADU', country: 'Uruguay' },
  { code: 'SACVEN', name: 'SACVEN', country: 'Venezuela' },
  { code: 'KODA', name: 'KODA', country: 'Denmark' },
  { code: 'STIM', name: 'STIM', country: 'Sweden' },
  { code: 'TONO', name: 'TONO', country: 'Norway' },
  { code: 'TEOSTO', name: 'Teosto', country: 'Finland' },
  { code: 'AKM', name: 'AKM', country: 'Austria' },
  { code: 'ZAIKS', name: 'ZAIKS', country: 'Poland' },
  { code: 'ARTISJUS', name: 'Artisjus', country: 'Hungary' },
  { code: 'OSA', name: 'OSA', country: 'Czech Republic' },
  { code: 'IMRO', name: 'IMRO', country: 'Ireland' },
  { code: 'SAMRO', name: 'SAMRO', country: 'South Africa' },
  { code: 'COMPASS', name: 'COMPASS', country: 'Singapore' },
  { code: 'IPRS', name: 'IPRS', country: 'India' },
  { code: 'MACP', name: 'MACP', country: 'Malaysia' },
  { code: 'FILSCAP', name: 'FILSCAP', country: 'Philippines' },
  { code: 'CASH', name: 'CASH', country: 'Hong Kong' },
  { code: 'MUST', name: 'MUST', country: 'Taiwan' },
  { code: 'MCSC', name: 'MCSC', country: 'China' },
  { code: 'RAO', name: 'RAO', country: 'Russia' },
  { code: 'ACUM', name: 'ACUM', country: 'Israel' },
  { code: 'MSG', name: 'MSG', country: 'Turkey' }
];

// Validation patterns for work IDs
export const workIdValidation = {
  ISWC: /^T-\d{3}\.\d{3}\.\d{3}-\d$/,
  ASCAP: /^\d{9}$/,
  BMI: /^\d{7,8}$/,
  SESAC: /^\d{10}$/,
  ISRC: /^[A-Z]{2}[A-Z0-9]{3}\d{2}\d{5}$/
};

// Languages for music
export const musicLanguages = [
  'Instrumental',
  'Afrikaans', 'Albanian', 'Amharic', 'Arabic', 'Armenian', 'Azerbaijani',
  'Basque', 'Belarusian', 'Bengali', 'Bosnian', 'Bulgarian', 'Burmese',
  'Catalan', 'Cebuano', 'Chichewa', 'Chinese (Cantonese)', 'Chinese (Mandarin)',
  'Corsican', 'Croatian', 'Czech','Danish', 'Dutch', 'Dzongkha', 'English', 'Esperanto',
  'Estonian','Filipino', 'Finnish', 'French', 'Frisian', 'Fula','Galician', 'Georgian',
  'German', 'Greek', 'Guarani', 'Gujarati', 'Haitian Creole', 'Hausa', 'Hawaiian',
  'Hebrew', 'Hindi', 'Hmong', 'Hungarian', 'Icelandic', 'Igbo', 'Ilocano', 'Indonesian',
  'Irish', 'Italian', 'Japanese', 'Javanese', 'Kannada', 'Kazakh', 'Khmer', 'Kinyarwanda',
  'Korean', 'Kurdish (Kurmanji)', 'Kurdish (Sorani)','Lao', 'Latin', 'Latvian', 'Lingala',
  'Lithuanian', 'Luxembourgish', 'Macedonian', 'Malagasy', 'Malay', 'Malayalam', 'Maltese',
  'Maori', 'Marathi', 'Mongolian', 'Nepali', 'Norwegian','Pashto', 'Persian', 'Polish',
  'Portuguese', 'Punjabi', 'Quechua', 'Romanian', 'Russian','Samoan', 'Sanskrit',
  'Scottish Gaelic', 'Serbian', 'Shona', 'Sindhi', 'Sinhala', 'Slovak', 'Slovenian',
  'Somali', 'Spanish', 'Sundanese', 'Swahili', 'Swedish', 'Tagalog', 'Tajik', 'Tamil',
  'Tatar', 'Telugu', 'Thai', 'Tibetan', 'Tigrinya', 'Turkish', 'Turkmen', 'Ukrainian',
  'Urdu', 'Uyghur', 'Uzbek', 'Vietnamese', 'Welsh', 'Wolof', 'Xhosa','Yiddish', 'Yoruba', 'Zulu'
];

export const usStates = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VI', name: 'Virgin Islands' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'GU', name: 'Guam' },
  { code: 'MP', name: 'Northern Mariana Islands' }
];

// Export genres and subgenres for easier access
export const musicGenres = Object.keys(genreSubgenreMap);
export const musicSubgenres = genreSubgenreMap;

// Add explicit content options
export const explicitContentOptions = ['Not Explicit', 'Explicit', 'Clean'];

// Add release types
export const releaseTypes = ['Single', 'EP', 'Album'];

// Add audio format specifications
export const audioFormats = {
  accepted: ['.aiff', '.flac', '.wav'],
  lossless: {
    sampleRates: [44100, 48000],
    bitDepths: [16, 24],
    channels: 2
  },
  hiRes: {
    sampleRates: [88200, 96000, 176400, 192000],
    bitDepths: [24],
    channels: 2
  }
};